<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>180</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>1</X>
      <Y>1</Y>
    </Node>
    <Node>
      <X>2</X>
      <Y>1</Y>
    </Node>
    <Node>
      <X>3</X>
      <Y>1</Y>
    </Node>
    <Node>
      <X>3</X>
      <Y>2</Y>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>3</X>
      <Y>3</Y>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID />
  <MetaData>
    <PuzzleTitle>Square/SquarePuzzle_2x2</PuzzleTitle>
    <BackgroundColor>LightGray</BackgroundColor>
    <ForegroundColor>DarkGray</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>1</X>
            <Y>2</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>1</X>
            <Y>3</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>1</X>
            <Y>4</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>1</X>
            <Y>5</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>1</X>
            <Y>6</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
          </Node>
          <Node>
            <X>1</X>
            <Y>7</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>1</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
          </Node>
          <Node>
            <X>7</X>
            <Y>7</Y>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Yellow</LineColor>
  </MetaData>
</SaveState>