<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>180</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>1.8872565345372749</X>
      <Y>0.43754273257012039</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.5210112020639013</X>
      <Y>-0.25958740170916705</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.2455799336665674</X>
      <Y>1.0792193334408282</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.6514349328603561</X>
      <Y>2.0000000000000013</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>3</X>
      <Y>3</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.3924238699130083</X>
      <Y>0.11061889743624891</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.6300818702354922</X>
      <Y>0.76813936499512225</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.6142380035473272</X>
      <Y>1.4652694992744098</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.3528142031925938</X>
      <Y>2.0039609666720408</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.7269814690100524</X>
      <Y>2.3287602337794362</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.1724461349242556</X>
      <Y>2.3762918338439332</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>7</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6.5</X>
      <Y>0.13397459621556118</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>7.5</X>
      <Y>0.13397459621556096</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>8</X>
      <Y>0.99999999999999956</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6.9999999999999991</X>
      <Y>-0.73205080756887775</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>8</X>
      <Y>-0.73205080756887886</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>8.5000000000000018</X>
      <Y>0.13397459621556018</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>9.0000000000000018</X>
      <Y>1.0000000000000004</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>7.4999999999999982</X>
      <Y>-1.5980762113533178</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>8.5</X>
      <Y>1.8660254037844382</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>8</X>
      <Y>2.7320508075688772</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>7.0000000000000009</X>
      <Y>2.7320508075688776</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6.5</X>
      <Y>1.8660254037844397</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6.5000000000000018</X>
      <Y>3.5980762113533169</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5.5000000000000018</X>
      <Y>3.5980762113533182</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5.0000000000000009</X>
      <Y>2.7320508075688803</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5.4999999999999991</X>
      <Y>1.866025403784441</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>8.5</X>
      <Y>3.5980762113533151</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>8</X>
      <Y>4.4641016151377535</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>7.0000000000000018</X>
      <Y>4.4641016151377535</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>9.5</X>
      <Y>1.8660254037844379</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>10</X>
      <Y>2.7320508075688767</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>9.5000000000000018</X>
      <Y>3.5980762113533156</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6.0000000000000036</X>
      <Y>4.4641016151377562</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>9</X>
      <Y>4.4641016151377535</Y>
      <Hidden>false</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>17</End>
      <Decorator xsi:type="EndDecorator">
        <Length>1</Length>
        <Angle>-90</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>20</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>22</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>25</Start>
      <End>26</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>27</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>27</Start>
      <End>28</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>29</Start>
      <End>30</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>31</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>32</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>33</Start>
      <End>34</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>35</Start>
      <End>26</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>25</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>31</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>30</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>29</Start>
      <End>36</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>36</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>32</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>12</int>
        <int>11</int>
        <int>13</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>12</int>
        <int>13</int>
        <int>14</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>12</int>
        <int>14</int>
        <int>15</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>14</int>
        <int>13</int>
        <int>16</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>14</int>
        <int>16</int>
        <int>17</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>14</int>
        <int>17</int>
        <int>18</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>14</int>
        <int>18</int>
        <int>15</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>15</int>
        <int>18</int>
        <int>19</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>17</int>
        <int>16</int>
        <int>20</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>12</int>
        <int>15</int>
        <int>21</int>
        <int>22</int>
        <int>23</int>
        <int>24</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>24</int>
        <int>23</int>
        <int>25</int>
        <int>26</int>
        <int>27</int>
        <int>28</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>23</int>
        <int>22</int>
        <int>29</int>
        <int>30</int>
        <int>31</int>
        <int>25</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>22</int>
        <int>21</int>
        <int>32</int>
        <int>33</int>
        <int>34</int>
        <int>29</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>12</int>
        <int>24</int>
        <int>11</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>24</int>
        <int>28</int>
        <int>11</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>26</int>
        <int>25</int>
        <int>35</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>25</int>
        <int>31</int>
        <int>35</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>30</int>
        <int>29</int>
        <int>36</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>29</int>
        <int>34</int>
        <int>36</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>32</int>
        <int>21</int>
        <int>19</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>21</int>
        <int>15</int>
        <int>19</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle />
    <BackgroundColor>#804000</BackgroundColor>
    <ForegroundColor>Black</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Orange</LineColor>
  </MetaData>
</SaveState>