<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <X>1</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.99999999999999978</X>
      <Y>0</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>-2.2204460492503131E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.2204460492503131E-16</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.86602540378443871</X>
      <Y>2.5000000000000004</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.7320508075688776</X>
      <Y>2.0000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.7320508075688779</X>
      <Y>1.0000000000000007</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.86602540378443982</X>
      <Y>0.5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.2320508075688785</X>
      <Y>0.13397459621556274</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.3660254037844406</X>
      <Y>-0.36602540378443826</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.36602540378444004</X>
      <Y>-0.36602540378443971</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.49999999999999989</X>
      <Y>0.13397459621556018</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.73205080756888</X>
      <Y>-0.73205080756887508</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.8660254037844417</X>
      <Y>-1.2320508075688763</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.2320508075688812</X>
      <Y>-1.5980762113533131</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.3660254037844428</X>
      <Y>-2.0980762113533147</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5000000000000044</X>
      <Y>-2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.0000000000000031</X>
      <Y>-1.7320508075688776</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.7320508075688776</X>
      <Y>2.0000000000000013</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.7320508075688785</X>
      <Y>1.0000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.7320508075688781</X>
      <Y>2.0000000000000027</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.7320508075688794</X>
      <Y>1.0000000000000018</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.3660254037844379</X>
      <Y>3.3660254037844393</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.2320508075688772</X>
      <Y>2.86602540378444</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.50000000000000056</X>
      <Y>2.8660254037844384</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.36602540378443815</X>
      <Y>3.3660254037844393</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.8660254037844368</X>
      <Y>4.2320508075688785</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.7320508075688763</X>
      <Y>3.7320508075688794</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>-4.4408920985006262E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.0000000000000004</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.0000000000000016</X>
      <Y>3.7320508075688767</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.13397459621556285</X>
      <Y>4.2320508075688785</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5000000000000036</X>
      <Y>4.5980762113533151</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.63397459621556473</X>
      <Y>5.0980762113533178</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.0000000000000062</X>
      <Y>5.4641016151377535</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.1339745962155674</X>
      <Y>5.9641016151377571</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.3660254037844357</X>
      <Y>5.0980762113533178</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.2320508075688754</X>
      <Y>4.59807621135332</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.49999999999999845</X>
      <Y>3.8660254037844379</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.99999999999999734</X>
      <Y>4.7320508075688776</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.7320508075688785</X>
      <Y>2.0000000000000044</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.73205080756888</X>
      <Y>1.0000000000000031</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.13397459621555963</X>
      <Y>-1.2320508075688799</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.99999999999999989</X>
      <Y>-0.73205080756888</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.63397459621555929</X>
      <Y>-2.09807621135332</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>-1.5980762113533205</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.63397459621555763</X>
      <Y>-3.0980762113533218</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>1.4999999999999971</X>
      <Y>-3.598076211353324</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>330</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>2.3660254037844375</X>
      <Y>-3.0980762113533244</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.3660254037844397</X>
      <Y>-2.0980762113533231</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.7320508075688759</X>
      <Y>3.0000000000000031</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.7320508075688767</X>
      <Y>3.0000000000000053</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.5980762113533178</X>
      <Y>2.5000000000000071</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-6.4641016151377588</X>
      <Y>2.000000000000008</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>210</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-6.4641016151377606</X>
      <Y>1.0000000000000064</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.5980762113533213</X>
      <Y>0.50000000000000389</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.0980762113533213</X>
      <Y>-2.098076211353312</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-4.0980762113533231</X>
      <Y>-3.0980762113533129</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>270</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-3.2320508075688847</X>
      <Y>-3.5980762113533142</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.3660254037844446</X>
      <Y>-3.098076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.8660254037844388</X>
      <Y>-0.50000000000000133</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>4.7320508075688785</X>
      <Y>-1.3322676295501879E-15</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>30</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>4.7320508075688785</X>
      <Y>0.99999999999999889</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.8660254037844406</X>
      <Y>1.5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.8660254037844481</X>
      <Y>5.9641016151377517</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>2.8660254037844513</X>
      <Y>6.9641016151377544</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>90</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>2.0000000000000124</X>
      <Y>7.4641016151377571</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.1339745962155707</X>
      <Y>6.96410161513776</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.3660254037844335</X>
      <Y>6.0980762113533178</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-3.2320508075688714</X>
      <Y>6.59807621135332</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>150</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-4.0980762113533107</X>
      <Y>6.0980762113533222</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.0980762113533133</X>
      <Y>5.0980762113533222</Y>
      <Hidden>false</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>0</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>20</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>22</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>25</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>27</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>26</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>27</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>29</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>28</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>31</Start>
      <End>27</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>30</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>33</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>32</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>35</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>34</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>37</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>36</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>39</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>38</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>38</Start>
      <End>39</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>41</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>40</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>40</Start>
      <End>41</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>43</Start>
      <End>30</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>42</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>42</Start>
      <End>43</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>45</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>44</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>44</Start>
      <End>45</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>47</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>46</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>46</Start>
      <End>47</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>49</Start>
      <End>47</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>46</Start>
      <End>48</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>48</Start>
      <End>49</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>53</Start>
      <End>49</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>48</Start>
      <End>50</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>50</Start>
      <End>51</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>51</Start>
      <End>52</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>52</Start>
      <End>53</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>55</Start>
      <End>44</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>54</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>54</Start>
      <End>55</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>59</Start>
      <End>45</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>44</Start>
      <End>56</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>56</Start>
      <End>57</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>57</Start>
      <End>58</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>58</Start>
      <End>59</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>63</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>60</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>60</Start>
      <End>61</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>61</Start>
      <End>62</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>62</Start>
      <End>63</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>67</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>64</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>64</Start>
      <End>65</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>65</Start>
      <End>66</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>66</Start>
      <End>67</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>71</Start>
      <End>39</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>38</Start>
      <End>68</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>68</Start>
      <End>69</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>69</Start>
      <End>70</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>70</Start>
      <End>71</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>75</Start>
      <End>41</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>40</Start>
      <End>72</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>72</Start>
      <End>73</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>73</Start>
      <End>74</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>74</Start>
      <End>75</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>2</int>
        <int>3</int>
        <int>1</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>0</int>
        <int>4</int>
        <int>5</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>1</int>
        <int>6</int>
        <int>7</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>7</int>
        <int>6</int>
        <int>8</int>
        <int>9</int>
        <int>10</int>
        <int>11</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Microsoft YaHei UI</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>房</Text>
        <Color>Yellow</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>11</int>
        <int>10</int>
        <int>12</int>
        <int>13</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>7</int>
        <int>11</int>
        <int>14</int>
        <int>15</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>13</int>
        <int>12</int>
        <int>16</int>
        <int>17</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>17</int>
        <int>16</int>
        <int>18</int>
        <int>19</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>17</int>
        <int>19</int>
        <int>20</int>
        <int>21</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>10</int>
        <int>9</int>
        <int>22</int>
        <int>23</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>23</int>
        <int>22</int>
        <int>24</int>
        <int>25</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>9</int>
        <int>8</int>
        <int>26</int>
        <int>27</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>8</int>
        <int>6</int>
        <int>28</int>
        <int>29</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>27</int>
        <int>26</int>
        <int>30</int>
        <int>31</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>5</int>
        <int>32</int>
        <int>33</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>29</int>
        <int>28</int>
        <int>34</int>
        <int>35</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>35</int>
        <int>34</int>
        <int>36</int>
        <int>37</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>37</int>
        <int>36</int>
        <int>38</int>
        <int>39</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>31</int>
        <int>30</int>
        <int>40</int>
        <int>41</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>30</int>
        <int>26</int>
        <int>42</int>
        <int>43</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>25</int>
        <int>24</int>
        <int>44</int>
        <int>45</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>15</int>
        <int>14</int>
        <int>46</int>
        <int>47</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>47</int>
        <int>46</int>
        <int>48</int>
        <int>49</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>49</int>
        <int>48</int>
        <int>50</int>
        <int>51</int>
        <int>52</int>
        <int>53</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Microsoft YaHei UI</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>房</Text>
        <Color>Yellow</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>44</int>
        <int>24</int>
        <int>54</int>
        <int>55</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>45</int>
        <int>44</int>
        <int>56</int>
        <int>57</int>
        <int>58</int>
        <int>59</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Microsoft YaHei UI</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>房</Text>
        <Color>Yellow</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>19</int>
        <int>18</int>
        <int>60</int>
        <int>61</int>
        <int>62</int>
        <int>63</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Microsoft YaHei UI</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>房</Text>
        <Color>Yellow</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>33</int>
        <int>32</int>
        <int>64</int>
        <int>65</int>
        <int>66</int>
        <int>67</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Microsoft YaHei UI</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>房</Text>
        <Color>Yellow</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>39</int>
        <int>38</int>
        <int>68</int>
        <int>69</int>
        <int>70</int>
        <int>71</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Microsoft YaHei UI</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>房</Text>
        <Color>Yellow</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>41</int>
        <int>40</int>
        <int>72</int>
        <int>73</int>
        <int>74</int>
        <int>75</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Microsoft YaHei UI</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>房</Text>
        <Color>Yellow</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle>Square/SquarePuzzle_1x1</PuzzleTitle>
    <BackgroundColor>Black</BackgroundColor>
    <ForegroundColor>Silver</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>#191919</LineColor>
  </MetaData>
</SaveState>