<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <X>-0.375</X>
      <Y>0</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>0</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-1.5</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>5.1961524227066338</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>6.4951905283832891</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>6.4951905283832891</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>-90</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-2.6250000000000004</X>
      <Y>1.1102230246251565E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.8750000000000004</X>
      <Y>-4.4408920985006262E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.8749999999999991</X>
      <Y>6.4951905283832891</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.6249999999999987</X>
      <Y>6.4951905283832891</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.924038105676658</X>
      <Y>1.2990381056766589</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.9240381056766589</X>
      <Y>5.5511151231257837E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.924038105676654</X>
      <Y>6.4951905283832909</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.9240381056766553</X>
      <Y>5.1961524227066356</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.223076211353316</X>
      <Y>1.29903810567666</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.2230762113533178</X>
      <Y>1.4432899320127039E-15</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.9240381056766567</X>
      <Y>2.5980762113533169</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.2230762113533151</X>
      <Y>2.5980762113533182</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.9240381056766553</X>
      <Y>3.8971143170299754</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.2230762113533133</X>
      <Y>3.8971143170299767</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.2230762113533116</X>
      <Y>5.1961524227066347</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-5.2230762113533125</X>
      <Y>6.4951905283832909</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-6.522114317029974</X>
      <Y>1.299038105676662</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-6.5221143170299767</X>
      <Y>3.2196467714129548E-15</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-7.8211524227066329</X>
      <Y>1.2990381056766649</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-7.8211524227066356</X>
      <Y>5.8841820305133312E-15</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-6.5221143170299722</X>
      <Y>2.5980762113533205</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-7.82115242270663</X>
      <Y>2.598076211353324</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-6.52211431702997</X>
      <Y>3.8971143170299776</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-6.5221143170299687</X>
      <Y>5.1961524227066338</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-7.8211524227066267</X>
      <Y>3.897114317029982</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-7.8211524227066223</X>
      <Y>5.1961524227066391</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-6.52211431702997</X>
      <Y>6.4951905283832909</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-7.8211524227066169</X>
      <Y>6.4951905283832927</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-9.12019052838327</X>
      <Y>6.495190528383298</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-9.1201905283832758</X>
      <Y>5.1961524227066445</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-9.1201905283832847</X>
      <Y>3.8971143170299865</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-9.1201905283832883</X>
      <Y>2.5980762113533276</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-9.1201905283832918</X>
      <Y>1.2990381056766676</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-9.1201905283832954</X>
      <Y>8.5487172896137085E-15</Y>
      <Hidden>false</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>14</End>
      <Decorator xsi:type="BrokenDecorator" />
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>39</Start>
      <End>40</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>41</Start>
      <End>42</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>43</Start>
      <End>44</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>45</Start>
      <End>46</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>48</Start>
      <End>49</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>50</Start>
      <End>51</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>52</Start>
      <End>53</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>27</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>38</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>40</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>42</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>44</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>46</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>39</Start>
      <End>47</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>41</Start>
      <End>49</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>43</Start>
      <End>51</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>45</Start>
      <End>53</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>20</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>22</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>25</Start>
      <End>26</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>27</Start>
      <End>28</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>29</Start>
      <End>30</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>31</Start>
      <End>32</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>33</Start>
      <End>34</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>35</Start>
      <End>36</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>38</Start>
      <End>39</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>40</Start>
      <End>41</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>42</Start>
      <End>43</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>44</Start>
      <End>45</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>47</Start>
      <End>48</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>49</Start>
      <End>50</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>51</Start>
      <End>52</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>55</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>54</Start>
      <End>55</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>50</Start>
      <End>56</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>56</Start>
      <End>57</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>54</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>57</Start>
      <End>48</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>59</Start>
      <End>54</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>58</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>58</Start>
      <End>59</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>61</Start>
      <End>48</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>57</Start>
      <End>60</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>60</Start>
      <End>61</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>63</Start>
      <End>59</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>58</Start>
      <End>62</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>62</Start>
      <End>63</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>65</Start>
      <End>62</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>58</Start>
      <End>64</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>64</Start>
      <End>65</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>67</Start>
      <End>65</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>64</Start>
      <End>66</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>66</Start>
      <End>67</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>68</Start>
      <End>67</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>66</Start>
      <End>61</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>61</Start>
      <End>68</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>69</Start>
      <End>68</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>60</Start>
      <End>69</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>71</Start>
      <End>63</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>62</Start>
      <End>70</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>70</Start>
      <End>71</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>73</Start>
      <End>71</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>70</Start>
      <End>72</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>72</Start>
      <End>73</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>74</Start>
      <End>70</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>65</Start>
      <End>74</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>75</Start>
      <End>72</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>74</Start>
      <End>75</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>76</Start>
      <End>74</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>67</Start>
      <End>76</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>77</Start>
      <End>76</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>68</Start>
      <End>77</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>78</Start>
      <End>75</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>76</Start>
      <End>78</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>79</Start>
      <End>78</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>77</Start>
      <End>79</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>80</Start>
      <End>77</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>69</Start>
      <End>80</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>81</Start>
      <End>79</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>80</Start>
      <End>81</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>83</Start>
      <End>79</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>81</Start>
      <End>82</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>82</Start>
      <End>83</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>84</Start>
      <End>78</End>
      <Decorator xsi:type="BrokenDecorator" />
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>83</Start>
      <End>84</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>85</Start>
      <End>75</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>84</Start>
      <End>85</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>86</Start>
      <End>72</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>85</Start>
      <End>86</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>87</Start>
      <End>73</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>86</Start>
      <End>87</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>66</Start>
      <End>39</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>64</Start>
      <End>28</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>1</int>
        <int>2</int>
        <int>10</int>
        <int>9</int>
        <int>8</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>3</int>
        <int>4</int>
        <int>12</int>
        <int>11</int>
        <int>10</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>4</int>
        <int>5</int>
        <int>6</int>
        <int>14</int>
        <int>13</int>
        <int>12</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>7</int>
        <int>8</int>
        <int>9</int>
        <int>19</int>
        <int>18</int>
        <int>17</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>9</int>
        <int>10</int>
        <int>11</int>
        <int>21</int>
        <int>20</int>
        <int>19</int>
      </Nodes>
      <Decorator xsi:type="CircleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Orange</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>11</int>
        <int>12</int>
        <int>13</int>
        <int>23</int>
        <int>22</int>
        <int>21</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Orange</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>13</int>
        <int>14</int>
        <int>15</int>
        <int>25</int>
        <int>24</int>
        <int>23</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>16</int>
        <int>17</int>
        <int>18</int>
        <int>29</int>
        <int>28</int>
        <int>27</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>18</int>
        <int>19</int>
        <int>20</int>
        <int>31</int>
        <int>30</int>
        <int>29</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>3</Count>
        <Color>Aqua</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>20</int>
        <int>21</int>
        <int>22</int>
        <int>33</int>
        <int>32</int>
        <int>31</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>3</Count>
        <Color>Aqua</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>22</int>
        <int>23</int>
        <int>24</int>
        <int>35</int>
        <int>34</int>
        <int>33</int>
      </Nodes>
      <Decorator xsi:type="RingDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Aqua</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>24</int>
        <int>25</int>
        <int>26</int>
        <int>37</int>
        <int>36</int>
        <int>35</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>28</int>
        <int>29</int>
        <int>30</int>
        <int>40</int>
        <int>39</int>
        <int>38</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>HotPink</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>30</int>
        <int>31</int>
        <int>32</int>
        <int>42</int>
        <int>41</int>
        <int>40</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>3</Count>
        <Color>HotPink</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>32</int>
        <int>33</int>
        <int>34</int>
        <int>44</int>
        <int>43</int>
        <int>42</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>34</int>
        <int>35</int>
        <int>36</int>
        <int>46</int>
        <int>45</int>
        <int>44</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>39</int>
        <int>40</int>
        <int>41</int>
        <int>49</int>
        <int>48</int>
        <int>47</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>41</int>
        <int>42</int>
        <int>43</int>
        <int>51</int>
        <int>50</int>
        <int>49</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>43</int>
        <int>44</int>
        <int>45</int>
        <int>53</int>
        <int>52</int>
        <int>51</int>
      </Nodes>
      <Decorator xsi:type="TetrisDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>-15</Angle>
        <ExtraScale>1</ExtraScale>
        <Shapes>
          <ArrayOfNode>
            <Node>
              <X>-0.375</X>
              <Y>3.897114317029974</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.375</X>
              <Y>3.897114317029974</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.75</X>
              <Y>4.546633369868303</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.375</X>
              <Y>5.196152422706632</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-0.375</X>
              <Y>5.196152422706632</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-0.75</X>
              <Y>4.546633369868303</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>0.75</X>
              <Y>4.546633369868303</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>1.5</X>
              <Y>4.546633369868303</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>1.875</X>
              <Y>5.196152422706632</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>1.5</X>
              <Y>5.84567147554496</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.75</X>
              <Y>5.84567147554496</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.375</X>
              <Y>5.196152422706632</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>-0.375</X>
              <Y>5.196152422706632</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.375</X>
              <Y>5.196152422706632</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.75</X>
              <Y>5.84567147554496</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.375</X>
              <Y>6.4951905283832891</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-0.375</X>
              <Y>6.4951905283832891</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-0.75</X>
              <Y>5.84567147554496</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
        </Shapes>
        <Indexes>
          <int>14</int>
          <int>15</int>
          <int>18</int>
        </Indexes>
        <Color>Orange</Color>
        <MarginSize>0.14</MarginSize>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>54</int>
        <int>55</int>
        <int>7</int>
        <int>17</int>
        <int>16</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>48</int>
        <int>49</int>
        <int>50</int>
        <int>56</int>
        <int>57</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>54</int>
        <int>16</int>
        <int>58</int>
        <int>59</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>48</int>
        <int>57</int>
        <int>60</int>
        <int>61</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>59</int>
        <int>58</int>
        <int>62</int>
        <int>63</int>
      </Nodes>
      <Decorator xsi:type="TetrisDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>-15</Angle>
        <ExtraScale>1</ExtraScale>
        <Shapes>
          <ArrayOfNode>
            <Node>
              <X>-5.2230762113533178</X>
              <Y>1.4432899320127039E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-5.223076211353316</X>
              <Y>1.29903810567666</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.522114317029974</X>
              <Y>1.299038105676662</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.5221143170299767</X>
              <Y>3.2196467714129548E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>-6.5221143170299767</X>
              <Y>3.2196467714129548E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.522114317029974</X>
              <Y>1.299038105676662</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066329</X>
              <Y>1.2990381056766649</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066356</X>
              <Y>5.8841820305133312E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>-7.8211524227066356</X>
              <Y>5.8841820305133312E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066329</X>
              <Y>1.2990381056766649</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-9.1201905283832918</X>
              <Y>1.2990381056766676</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-9.1201905283832954</X>
              <Y>8.5487172896137085E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
        </Shapes>
        <Indexes>
          <int>28</int>
          <int>29</int>
          <int>42</int>
        </Indexes>
        <Color>Orange</Color>
        <MarginSize>0.14</MarginSize>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>62</int>
        <int>58</int>
        <int>64</int>
        <int>65</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>65</int>
        <int>64</int>
        <int>66</int>
        <int>67</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>67</int>
        <int>66</int>
        <int>61</int>
        <int>68</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>68</int>
        <int>61</int>
        <int>60</int>
        <int>69</int>
      </Nodes>
      <Decorator xsi:type="TetrisDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>-15</Angle>
        <ExtraScale>1</ExtraScale>
        <Shapes>
          <ArrayOfNode>
            <Node>
              <X>-5.2230762113533178</X>
              <Y>1.4432899320127039E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-5.223076211353316</X>
              <Y>1.29903810567666</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.522114317029974</X>
              <Y>1.299038105676662</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.5221143170299767</X>
              <Y>3.2196467714129548E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>-6.5221143170299767</X>
              <Y>3.2196467714129548E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.522114317029974</X>
              <Y>1.299038105676662</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066329</X>
              <Y>1.2990381056766649</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066356</X>
              <Y>5.8841820305133312E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>-7.8211524227066356</X>
              <Y>5.8841820305133312E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066329</X>
              <Y>1.2990381056766649</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-9.1201905283832918</X>
              <Y>1.2990381056766676</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-9.1201905283832954</X>
              <Y>8.5487172896137085E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
        </Shapes>
        <Indexes>
          <int>28</int>
          <int>29</int>
          <int>42</int>
        </Indexes>
        <Color>Orange</Color>
        <MarginSize>0.14</MarginSize>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>63</int>
        <int>62</int>
        <int>70</int>
        <int>71</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>71</int>
        <int>70</int>
        <int>72</int>
        <int>73</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>70</int>
        <int>62</int>
        <int>65</int>
        <int>74</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>1</Count>
        <Color>HotPink</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>72</int>
        <int>70</int>
        <int>74</int>
        <int>75</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>74</int>
        <int>65</int>
        <int>67</int>
        <int>76</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>76</int>
        <int>67</int>
        <int>68</int>
        <int>77</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>75</int>
        <int>74</int>
        <int>76</int>
        <int>78</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>78</int>
        <int>76</int>
        <int>77</int>
        <int>79</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>1</Count>
        <Color>HotPink</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>77</int>
        <int>68</int>
        <int>69</int>
        <int>80</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>79</int>
        <int>77</int>
        <int>80</int>
        <int>81</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>79</int>
        <int>81</int>
        <int>82</int>
        <int>83</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>78</int>
        <int>79</int>
        <int>83</int>
        <int>84</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>75</int>
        <int>78</int>
        <int>84</int>
        <int>85</int>
      </Nodes>
      <Decorator xsi:type="HollowTetrisDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Shapes>
          <ArrayOfNode>
            <Node>
              <X>-5.2230762113533178</X>
              <Y>1.4432899320127039E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-5.223076211353316</X>
              <Y>1.29903810567666</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.522114317029974</X>
              <Y>1.299038105676662</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.5221143170299767</X>
              <Y>3.2196467714129548E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>-6.5221143170299767</X>
              <Y>3.2196467714129548E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-6.522114317029974</X>
              <Y>1.299038105676662</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066329</X>
              <Y>1.2990381056766649</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066356</X>
              <Y>5.8841820305133312E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>-7.8211524227066356</X>
              <Y>5.8841820305133312E-15</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-7.8211524227066329</X>
              <Y>1.2990381056766649</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-9.1201905283832918</X>
              <Y>1.2990381056766676</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>-9.1201905283832954</X>
              <Y>8.5487172896137085E-15</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
        </Shapes>
        <Indexes>
          <int>28</int>
          <int>29</int>
          <int>42</int>
        </Indexes>
        <Color>Aqua</Color>
        <BorderSize>0.26</BorderSize>
        <MarginSize>0.14</MarginSize>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>72</int>
        <int>75</int>
        <int>85</int>
        <int>86</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>73</int>
        <int>72</int>
        <int>86</int>
        <int>87</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>1</Count>
        <Color>HotPink</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>66</int>
        <int>39</int>
        <int>47</int>
        <int>48</int>
        <int>61</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>66</int>
        <int>64</int>
        <int>28</int>
        <int>38</int>
        <int>39</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>64</int>
        <int>58</int>
        <int>16</int>
        <int>27</int>
        <int>28</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle>HexRound/HexRoundPuzzle_5x5</PuzzleTitle>
    <BackgroundColor>SaddleBrown</BackgroundColor>
    <ForegroundColor>BurlyWood</ForegroundColor>
    <EdgeWidth>0.15</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>0</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>0</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.6250000000000004</X>
            <Y>1.1102230246251565E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.8750000000000004</X>
            <Y>-4.4408920985006262E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.8749999999999991</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.6249999999999987</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.6250000000000004</X>
            <Y>1.1102230246251565E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.924038105676658</X>
            <Y>1.2990381056766589</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766589</X>
            <Y>5.5511151231257837E-16</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.6249999999999987</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.924038105676654</X>
            <Y>6.4951905283832909</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>5.1961524227066356</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.9240381056766589</X>
            <Y>5.5511151231257837E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.924038105676658</X>
            <Y>1.2990381056766589</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.223076211353316</X>
            <Y>1.29903810567666</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533178</X>
            <Y>1.4432899320127039E-15</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.223076211353316</X>
            <Y>1.29903810567666</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.924038105676658</X>
            <Y>1.2990381056766589</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766567</X>
            <Y>2.5980762113533169</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533151</X>
            <Y>2.5980762113533182</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.2230762113533151</X>
            <Y>2.5980762113533182</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766567</X>
            <Y>2.5980762113533169</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>3.8971143170299754</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533133</X>
            <Y>3.8971143170299767</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.2230762113533133</X>
            <Y>3.8971143170299767</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>3.8971143170299754</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>5.1961524227066356</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533116</X>
            <Y>5.1961524227066347</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.2230762113533116</X>
            <Y>5.1961524227066347</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>5.1961524227066356</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.924038105676654</X>
            <Y>6.4951905283832909</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533125</X>
            <Y>6.4951905283832909</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.2230762113533178</X>
            <Y>1.4432899320127039E-15</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.223076211353316</X>
            <Y>1.29903810567666</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.522114317029974</X>
            <Y>1.299038105676662</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.5221143170299767</X>
            <Y>3.2196467714129548E-15</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.5221143170299767</X>
            <Y>3.2196467714129548E-15</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.522114317029974</X>
            <Y>1.299038105676662</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066329</X>
            <Y>1.2990381056766649</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066356</X>
            <Y>5.8841820305133312E-15</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.522114317029974</X>
            <Y>1.299038105676662</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.223076211353316</X>
            <Y>1.29903810567666</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533151</X>
            <Y>2.5980762113533182</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.5221143170299722</X>
            <Y>2.5980762113533205</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.8211524227066329</X>
            <Y>1.2990381056766649</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.522114317029974</X>
            <Y>1.299038105676662</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.5221143170299722</X>
            <Y>2.5980762113533205</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.82115242270663</X>
            <Y>2.598076211353324</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.5221143170299722</X>
            <Y>2.5980762113533205</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533151</X>
            <Y>2.5980762113533182</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533133</X>
            <Y>3.8971143170299767</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.52211431702997</X>
            <Y>3.8971143170299776</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.52211431702997</X>
            <Y>3.8971143170299776</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533133</X>
            <Y>3.8971143170299767</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533116</X>
            <Y>5.1961524227066347</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.5221143170299687</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.82115242270663</X>
            <Y>2.598076211353324</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.5221143170299722</X>
            <Y>2.5980762113533205</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.52211431702997</X>
            <Y>3.8971143170299776</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066267</X>
            <Y>3.897114317029982</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.8211524227066267</X>
            <Y>3.897114317029982</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.52211431702997</X>
            <Y>3.8971143170299776</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.5221143170299687</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066223</X>
            <Y>5.1961524227066391</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.5221143170299687</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533116</X>
            <Y>5.1961524227066347</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.2230762113533125</X>
            <Y>6.4951905283832909</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.52211431702997</X>
            <Y>6.4951905283832909</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.8211524227066223</X>
            <Y>5.1961524227066391</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.5221143170299687</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.52211431702997</X>
            <Y>6.4951905283832909</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066169</X>
            <Y>6.4951905283832927</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.8211524227066223</X>
            <Y>5.1961524227066391</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066169</X>
            <Y>6.4951905283832927</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.12019052838327</X>
            <Y>6.495190528383298</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832758</X>
            <Y>5.1961524227066445</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.8211524227066267</X>
            <Y>3.897114317029982</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066223</X>
            <Y>5.1961524227066391</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832758</X>
            <Y>5.1961524227066445</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832847</X>
            <Y>3.8971143170299865</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.82115242270663</X>
            <Y>2.598076211353324</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066267</X>
            <Y>3.897114317029982</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832847</X>
            <Y>3.8971143170299865</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832883</X>
            <Y>2.5980762113533276</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.8211524227066329</X>
            <Y>1.2990381056766649</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.82115242270663</X>
            <Y>2.598076211353324</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832883</X>
            <Y>2.5980762113533276</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832918</X>
            <Y>1.2990381056766676</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.8211524227066356</X>
            <Y>5.8841820305133312E-15</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.8211524227066329</X>
            <Y>1.2990381056766649</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832918</X>
            <Y>1.2990381056766676</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1201905283832954</X>
            <Y>8.5487172896137085E-15</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>3.8971143170299754</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>5.1961524227066338</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>5.1961524227066356</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.9240381056766553</X>
            <Y>3.8971143170299754</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.9240381056766567</X>
            <Y>2.5980762113533169</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.9240381056766567</X>
            <Y>2.5980762113533169</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.924038105676658</X>
            <Y>1.2990381056766589</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.15</TetrisScale>
    <FaceDecorationScale>1.35</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Gold</LineColor>
  </MetaData>
</SaveState>