<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <X>1</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.8660254037844388</X>
      <Y>0.49999999999999978</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.7320508075688776</X>
      <Y>0.99999999999999978</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.7320508075688776</X>
      <Y>1.9999999999999996</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.8660254037844393</X>
      <Y>2.5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.8660254037844397</X>
      <Y>3.5000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.0000000000000009</X>
      <Y>4.0000000000000018</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.1339745962155616</X>
      <Y>3.5000000000000018</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.1339745962155605</X>
      <Y>2.5000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.13397459621556118</X>
      <Y>2.5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.73205080756887764</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.73205080756887764</X>
      <Y>1.0000000000000004</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.13397459621556052</X>
      <Y>0.49999999999999989</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.13397459621556018</X>
      <Y>-0.50000000000000133</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.99999999999999933</X>
      <Y>-1.0000000000000018</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.8660254037844388</X>
      <Y>-0.500000000000002</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.8660254037844397</X>
      <Y>0.49999999999999867</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.1339745962155614</X>
      <Y>3.5000000000000004</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.73205080756887742</X>
      <Y>4.0000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.598076211353316</X>
      <Y>3.5000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5980762113533169</X>
      <Y>2.5000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.8660254037844384</X>
      <Y>-0.50000000000000067</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.7320508075688776</X>
      <Y>-1.0000000000000011</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.598076211353316</X>
      <Y>-0.50000000000000111</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.5980762113533169</X>
      <Y>0.49999999999999889</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5980762113533191</X>
      <Y>0.50000000000000089</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.4641016151377544</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.4641016151377544</X>
      <Y>1.0000000000000007</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-2.4641016151377544</X>
      <Y>4.0000000000000018</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.3301270189221936</X>
      <Y>3.5000000000000027</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.3301270189221945</X>
      <Y>2.5000000000000027</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.5980762113533187</X>
      <Y>2.4999999999999991</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.5980762113533187</X>
      <Y>3.5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.7320508075688803</X>
      <Y>4.0000000000000009</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5.4641016151377553</X>
      <Y>0.99999999999999956</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5.4641016151377553</X>
      <Y>1.9999999999999991</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>-90</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>5.4641016151377544</X>
      <Y>-1.000000000000002</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6.3301270189221936</X>
      <Y>-0.50000000000000289</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>6.3301270189221945</X>
      <Y>0.499999999999997</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5980762113533196</X>
      <Y>-0.50000000000000044</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.73205080756888063</X>
      <Y>-1.0000000000000018</Y>
      <Hidden>false</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>0</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>0</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>20</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>22</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>27</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>25</Start>
      <End>26</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>27</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>28</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>29</Start>
      <End>30</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>28</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>31</Start>
      <End>32</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>33</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>34</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>35</Start>
      <End>36</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>27</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>37</Start>
      <End>38</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>38</Start>
      <End>34</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>39</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>39</Start>
      <End>40</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>40</Start>
      <End>41</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>41</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>43</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>42</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>42</Start>
      <End>43</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>3</int>
        <int>2</int>
        <int>4</int>
        <int>5</int>
        <int>6</int>
        <int>7</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>3</Count>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>3</int>
        <int>7</int>
        <int>8</int>
        <int>9</int>
        <int>10</int>
        <int>11</int>
      </Nodes>
      <Decorator xsi:type="SquareDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>LightCyan</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>1</int>
        <int>12</int>
        <int>13</int>
        <int>14</int>
        <int>15</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>2</Count>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>15</int>
        <int>16</int>
        <int>17</int>
        <int>18</int>
        <int>19</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>13</int>
        <int>12</int>
        <int>20</int>
        <int>21</int>
        <int>22</int>
        <int>23</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>5</int>
        <int>4</int>
        <int>24</int>
        <int>25</int>
        <int>26</int>
        <int>27</int>
      </Nodes>
      <Decorator xsi:type="RingDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>HotPink</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>14</int>
        <int>13</int>
        <int>23</int>
        <int>29</int>
        <int>30</int>
        <int>28</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>23</int>
        <int>22</int>
        <int>31</int>
        <int>32</int>
        <int>33</int>
        <int>29</int>
      </Nodes>
      <Decorator xsi:type="SquareDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>HotPink</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>8</int>
        <int>7</int>
        <int>6</int>
        <int>34</int>
        <int>35</int>
        <int>36</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>6</int>
        <int>5</int>
        <int>27</int>
        <int>37</int>
        <int>38</int>
        <int>34</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>27</int>
        <int>26</int>
        <int>39</int>
        <int>40</int>
        <int>41</int>
        <int>37</int>
      </Nodes>
      <Decorator xsi:type="SquareDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>24</int>
        <int>4</int>
        <int>19</int>
        <int>18</int>
      </Nodes>
      <Decorator xsi:type="CircleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>LightCyan</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>16</int>
        <int>15</int>
        <int>14</int>
        <int>28</int>
        <int>42</int>
        <int>43</int>
      </Nodes>
      <Decorator xsi:type="SquareDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>LightCyan</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle>Square/SquarePuzzle_1x1</PuzzleTitle>
    <BackgroundColor>SaddleBrown</BackgroundColor>
    <ForegroundColor>BurlyWood</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1.3</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Gold</LineColor>
  </MetaData>
</SaveState>