<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>-135</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-0.375</X>
      <Y>0</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>0.375</X>
      <Y>0</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>0.649519052838329</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>1.299038105676658</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3</X>
      <Y>1.948557158514987</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>2.598076211353316</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.875</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.625</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3</X>
      <Y>3.2475952641916446</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>3.897114317029974</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.375</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.375</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.75</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.5</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3</X>
      <Y>4.546633369868303</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-2.625</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.875</X>
      <Y>5.196152422706632</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-1.5</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-0.75</X>
      <Y>5.84567147554496</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-0.375</X>
      <Y>6.4951905283832891</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>45</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>0.375</X>
      <Y>6.4951905283832891</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="SymmetryPuzzleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SecondLineColor>Aqua</SecondLineColor>
        <IsRotational>true</IsRotational>
      </Decorator>
      <X>0</X>
      <Y>3.2475952641916446</Y>
      <Hidden>true</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>39</Start>
      <End>40</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>41</Start>
      <End>42</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>43</Start>
      <End>44</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>45</Start>
      <End>46</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>48</Start>
      <End>49</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>50</Start>
      <End>51</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>52</Start>
      <End>53</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>25</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>27</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>29</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>31</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>33</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>24</Start>
      <End>35</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>26</Start>
      <End>37</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>28</Start>
      <End>38</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>30</Start>
      <End>40</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>32</Start>
      <End>42</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>34</Start>
      <End>44</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>36</Start>
      <End>46</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>39</Start>
      <End>47</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>41</Start>
      <End>49</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>43</Start>
      <End>51</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>45</Start>
      <End>53</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>20</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>22</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>25</Start>
      <End>26</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>27</Start>
      <End>28</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>29</Start>
      <End>30</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>31</Start>
      <End>32</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>33</Start>
      <End>34</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>35</Start>
      <End>36</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>38</Start>
      <End>39</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>40</Start>
      <End>41</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>42</Start>
      <End>43</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>44</Start>
      <End>45</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>47</Start>
      <End>48</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>49</Start>
      <End>50</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>51</Start>
      <End>52</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>1</int>
        <int>2</int>
        <int>10</int>
        <int>9</int>
        <int>8</int>
      </Nodes>
      <Decorator xsi:type="EliminatorDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>SlateBlue</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>3</int>
        <int>4</int>
        <int>12</int>
        <int>11</int>
        <int>10</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>4</int>
        <int>5</int>
        <int>6</int>
        <int>14</int>
        <int>13</int>
        <int>12</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>2</Count>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>7</int>
        <int>8</int>
        <int>9</int>
        <int>19</int>
        <int>18</int>
        <int>17</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>9</int>
        <int>10</int>
        <int>11</int>
        <int>21</int>
        <int>20</int>
        <int>19</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>11</int>
        <int>12</int>
        <int>13</int>
        <int>23</int>
        <int>22</int>
        <int>21</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>13</int>
        <int>14</int>
        <int>15</int>
        <int>25</int>
        <int>24</int>
        <int>23</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>SlateBlue</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>16</int>
        <int>17</int>
        <int>18</int>
        <int>29</int>
        <int>28</int>
        <int>27</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>18</int>
        <int>19</int>
        <int>20</int>
        <int>31</int>
        <int>30</int>
        <int>29</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>20</int>
        <int>21</int>
        <int>22</int>
        <int>33</int>
        <int>32</int>
        <int>31</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>4</Count>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>22</int>
        <int>23</int>
        <int>24</int>
        <int>35</int>
        <int>34</int>
        <int>33</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>24</int>
        <int>25</int>
        <int>26</int>
        <int>37</int>
        <int>36</int>
        <int>35</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>28</int>
        <int>29</int>
        <int>30</int>
        <int>40</int>
        <int>39</int>
        <int>38</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>SlateBlue</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>30</int>
        <int>31</int>
        <int>32</int>
        <int>42</int>
        <int>41</int>
        <int>40</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>32</int>
        <int>33</int>
        <int>34</int>
        <int>44</int>
        <int>43</int>
        <int>42</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>34</int>
        <int>35</int>
        <int>36</int>
        <int>46</int>
        <int>45</int>
        <int>44</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>39</int>
        <int>40</int>
        <int>41</int>
        <int>49</int>
        <int>48</int>
        <int>47</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>41</int>
        <int>42</int>
        <int>43</int>
        <int>51</int>
        <int>50</int>
        <int>49</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>2</Count>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>43</int>
        <int>44</int>
        <int>45</int>
        <int>53</int>
        <int>52</int>
        <int>51</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>SlateBlue</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle>HexRound/HexRoundPuzzle_5x5</PuzzleTitle>
    <BackgroundColor>Navy</BackgroundColor>
    <ForegroundColor>CornflowerBlue</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>0</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>0</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4.125</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>0.649519052838329</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4.125</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>1.299038105676658</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4.125</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.75</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>1.948557158514987</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.125</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>2.598076211353316</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4.125</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.75</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>3.2475952641916446</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.125</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>3.897114317029974</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1.875</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.625</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.75</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>4.546633369868303</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.125</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>5.196152422706632</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.875</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.5</X>
            <Y>8.443747686898277</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>8.443747686898277</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.75</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>5.84567147554496</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.125</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.625</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>6.4951905283832891</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.625</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-1.5</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>7.144709581221619</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>8.443747686898277</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.5</X>
            <Y>8.443747686898277</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-1.875</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-0.375</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>7.794228634059948</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.75</X>
            <Y>8.443747686898277</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.375</X>
            <Y>9.093266739736606</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.375</X>
            <Y>9.093266739736606</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-0.75</X>
            <Y>8.443747686898277</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1.25</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Yellow</LineColor>
  </MetaData>
</SaveState>