<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>0</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-2.8284271247461903</X>
      <Y>-1.4142135623730947</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.5355339059327378</X>
      <Y>-2.1213203435596424</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>-90</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-4.2426406871192857</X>
      <Y>-2.8284271247461894</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>0</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-2.82842712474619</X>
      <Y>3.9523009633941837E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.5355339059327378</X>
      <Y>-0.707106781186547</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.2426406871192857</X>
      <Y>-1.4142135623730945</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.9497474683058327</X>
      <Y>-2.1213203435596415</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.5355339059327378</X>
      <Y>0.70710678118654813</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.2426406871192857</X>
      <Y>7.0386744697164325E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.9497474683058327</X>
      <Y>-0.70710678118654668</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>180</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-5.65685424949238</X>
      <Y>-1.414213562373094</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.2426406871192848</X>
      <Y>1.4142135623730956</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.9497474683058327</X>
      <Y>0.70710678118654824</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>180</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-5.65685424949238</X>
      <Y>7.9046019267883673E-16</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>0</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-2.82842712474619</X>
      <Y>1.4142135623730956</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-3.5355339059327373</X>
      <Y>2.1213203435596428</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>-4.9497474683058318</X>
      <Y>2.1213203435596433</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>180</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>-5.65685424949238</X>
      <Y>1.4142135623730958</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>-4.2426406871192848</X>
      <Y>2.8284271247461912</Y>
      <Hidden>false</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>4</int>
        <int>5</int>
        <int>1</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>1</int>
        <int>5</int>
        <int>6</int>
        <int>2</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Segoe UI Emoji</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>s:4096</Text>
        <Color>Silver</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>3</int>
        <int>7</int>
        <int>8</int>
        <int>4</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>4</int>
        <int>8</int>
        <int>9</int>
        <int>5</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Segoe UI Emoji</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>s:1</Text>
        <Color>Silver</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>5</int>
        <int>9</int>
        <int>10</int>
        <int>6</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>7</int>
        <int>11</int>
        <int>12</int>
        <int>8</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Segoe UI Emoji</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>s:4096</Text>
        <Color>Silver</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>8</int>
        <int>12</int>
        <int>13</int>
        <int>9</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>11</int>
        <int>7</int>
        <int>14</int>
        <int>15</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>12</int>
        <int>11</int>
        <int>16</int>
        <int>17</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>11</int>
        <int>15</int>
        <int>18</int>
        <int>16</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle>Square/SquarePuzzle_4x4</PuzzleTitle>
    <BackgroundColor>#404040</BackgroundColor>
    <ForegroundColor>Silver</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>-1.4142135623730949</X>
            <Y>1.9761504816970918E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.1213203435596424</X>
            <Y>0.70710678118654779</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.82842712474619</X>
            <Y>3.9523009633941837E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.1213203435596428</X>
            <Y>-0.70710678118654724</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.1213203435596428</X>
            <Y>-0.70710678118654724</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.82842712474619</X>
            <Y>3.9523009633941837E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>-0.707106781186547</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.8284271247461903</X>
            <Y>-1.4142135623730947</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.8284271247461903</X>
            <Y>-1.4142135623730947</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>-0.707106781186547</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>-1.4142135623730945</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>-2.1213203435596424</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>-2.1213203435596424</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>-1.4142135623730945</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.6568542494923806</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058336</X>
            <Y>-3.5355339059327369</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.9497474683058336</X>
            <Y>-3.5355339059327369</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.6568542494923806</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-3.5355339059327373</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>-4.2426406871192848</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.1213203435596424</X>
            <Y>0.70710678118654779</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.82842712474619</X>
            <Y>1.4142135623730956</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>0.70710678118654813</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-2.82842712474619</X>
            <Y>3.9523009633941837E-16</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.82842712474619</X>
            <Y>3.9523009633941837E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>0.70710678118654813</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>7.0386744697164325E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>-0.707106781186547</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>-0.707106781186547</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>7.0386744697164325E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-0.70710678118654668</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>-1.4142135623730945</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>-1.4142135623730945</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-0.70710678118654668</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.6568542494923806</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.6568542494923806</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-3.5355339059327373</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-2.82842712474619</X>
            <Y>1.4142135623730956</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327373</X>
            <Y>2.1213203435596428</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192848</X>
            <Y>1.4142135623730956</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>0.70710678118654813</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.5355339059327378</X>
            <Y>0.70710678118654813</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192848</X>
            <Y>1.4142135623730956</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>0.70710678118654824</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>7.0386744697164325E-16</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.2426406871192857</X>
            <Y>7.0386744697164325E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>0.70710678118654824</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>7.9046019267883673E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-0.70710678118654668</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>-0.70710678118654668</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>7.9046019267883673E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.65685424949238</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-2.1213203435596415</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520225</X>
            <Y>-2.1213203435596419</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>-2.8284271247461894</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-3.5355339059327373</X>
            <Y>2.1213203435596428</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192848</X>
            <Y>2.8284271247461907</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>2.1213203435596433</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.2426406871192848</X>
            <Y>1.4142135623730956</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.2426406871192848</X>
            <Y>1.4142135623730956</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>2.1213203435596433</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>1.4142135623730958</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>0.70710678118654824</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>0.70710678118654824</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>1.4142135623730958</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>0.70710678118654835</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>7.9046019267883673E-16</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.65685424949238</X>
            <Y>7.9046019267883673E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>0.70710678118654835</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>8.7705293838603041E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>8.7705293838603041E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520234</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>-1.414213562373094</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520234</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-8.48528137423857</X>
            <Y>-1.4142135623730945</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520225</X>
            <Y>-2.1213203435596419</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.2426406871192848</X>
            <Y>2.8284271247461907</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>3.5355339059327386</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>2.8284271247461912</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>2.1213203435596433</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>2.1213203435596433</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>2.8284271247461912</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>2.1213203435596437</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>1.4142135623730958</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.65685424949238</X>
            <Y>1.4142135623730958</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>2.1213203435596437</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>1.4142135623730963</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>0.70710678118654835</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>0.70710678118654835</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>1.4142135623730963</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520225</X>
            <Y>0.70710678118654879</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>8.7705293838603041E-16</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>8.7705293838603041E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520225</X>
            <Y>0.70710678118654879</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-8.4852813742385713</X>
            <Y>1.4077348939432865E-15</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520234</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.7781745930520234</X>
            <Y>-0.70710678118654657</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-8.4852813742385713</X>
            <Y>1.4077348939432865E-15</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1923881554251174</X>
            <Y>-0.70710678118654646</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-8.48528137423857</X>
            <Y>-1.4142135623730945</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-4.9497474683058327</X>
            <Y>3.5355339059327386</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.6568542494923806</X>
            <Y>4.2426406871192857</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>3.5355339059327382</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-5.65685424949238</X>
            <Y>2.8284271247461912</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-5.65685424949238</X>
            <Y>2.8284271247461912</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>3.5355339059327382</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>2.8284271247461907</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>2.1213203435596437</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-6.3639610306789276</X>
            <Y>2.1213203435596437</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>2.8284271247461907</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520234</X>
            <Y>2.1213203435596433</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>1.4142135623730963</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.0710678118654755</X>
            <Y>1.4142135623730963</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520234</X>
            <Y>2.1213203435596433</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-8.4852813742385713</X>
            <Y>1.4142135623730958</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-7.7781745930520225</X>
            <Y>0.70710678118654879</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-7.7781745930520225</X>
            <Y>0.70710678118654879</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-8.4852813742385713</X>
            <Y>1.4142135623730958</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1923881554251174</X>
            <Y>0.70710678118654846</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-8.4852813742385713</X>
            <Y>1.4077348939432865E-15</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>-8.4852813742385713</X>
            <Y>1.4077348939432865E-15</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1923881554251174</X>
            <Y>0.70710678118654846</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.8994949366116654</X>
            <Y>6.0614921995035485E-16</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>-9.1923881554251174</X>
            <Y>-0.70710678118654646</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Aqua</LineColor>
  </MetaData>
</SaveState>