<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <X>1</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1</X>
      <Y>3</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1</X>
      <Y>4</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>1</X>
      <Y>5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>3</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>4</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2</X>
      <Y>5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>3</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>4</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3</X>
      <Y>5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4</X>
      <Y>3</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4</X>
      <Y>4</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4</X>
      <Y>5</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>0</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>5</X>
      <Y>1</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5</X>
      <Y>2</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5</X>
      <Y>3</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5</X>
      <Y>4</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>5</X>
      <Y>5</Y>
      <Hidden>false</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>10</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>15</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>17</End>
      <Decorator xsi:type="PointDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Black</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>14</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>20</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>22</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>19</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>1</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>10</Start>
      <End>11</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>11</Start>
      <End>12</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>12</Start>
      <End>13</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>13</Start>
      <End>14</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>15</Start>
      <End>16</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>16</Start>
      <End>17</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>17</Start>
      <End>18</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>18</Start>
      <End>19</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>20</Start>
      <End>21</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>21</Start>
      <End>22</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>22</Start>
      <End>23</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>23</Start>
      <End>24</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>0</int>
        <int>5</int>
        <int>6</int>
        <int>1</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>1</int>
        <int>6</int>
        <int>7</int>
        <int>2</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Lime</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>7</int>
        <int>8</int>
        <int>3</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>-15</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Segoe UI Emoji</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>┣</Text>
        <Color>Lime</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>3</int>
        <int>8</int>
        <int>9</int>
        <int>4</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>5</int>
        <int>10</int>
        <int>11</int>
        <int>6</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>6</int>
        <int>11</int>
        <int>12</int>
        <int>7</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>-15</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Segoe UI Emoji</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>┣</Text>
        <Color>Lime</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>7</int>
        <int>12</int>
        <int>13</int>
        <int>8</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>8</int>
        <int>13</int>
        <int>14</int>
        <int>9</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>10</int>
        <int>15</int>
        <int>16</int>
        <int>11</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>11</int>
        <int>16</int>
        <int>17</int>
        <int>12</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>12</int>
        <int>17</int>
        <int>18</int>
        <int>13</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>-15</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Segoe UI Emoji</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>┣</Text>
        <Color>Lime</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>13</int>
        <int>18</int>
        <int>19</int>
        <int>14</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>15</int>
        <int>20</int>
        <int>21</int>
        <int>16</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>16</int>
        <int>21</int>
        <int>22</int>
        <int>17</int>
      </Nodes>
      <Decorator xsi:type="TextDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>-15</Angle>
        <ExtraScale>1</ExtraScale>
        <SerializableFont>
          <FontFamily>Segoe UI Emoji</FontFamily>
          <GraphicsUnit>Point</GraphicsUnit>
          <Size>9</Size>
          <Style>Regular</Style>
        </SerializableFont>
        <Text>┣</Text>
        <Color>Lime</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>17</int>
        <int>22</int>
        <int>23</int>
        <int>18</int>
      </Nodes>
      <Decorator xsi:type="StarDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Color>Lime</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>18</int>
        <int>23</int>
        <int>24</int>
        <int>19</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle>Square/SquarePuzzle_4x4</PuzzleTitle>
    <BackgroundColor>#404040</BackgroundColor>
    <ForegroundColor>Silver</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>1</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>4</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>5</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>1</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>2</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>3</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>4</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>5</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>6</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>6</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>7</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>6</X>
            <Y>7</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Aqua</LineColor>
  </MetaData>
</SaveState>