<?xml version="1.0"?>
<SaveState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Nodes>
    <Node>
      <X>1.7424000000000002</X>
      <Y>1.7424000000000002</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.4848000000000003</X>
      <Y>1.7424000000000002</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.6135999999999995</X>
      <Y>0.23343733644599379</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>0.87119999999999886</X>
      <Y>0.23343733644599501</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="StartDecorator">
        <Color>Transparent</Color>
      </Decorator>
      <X>2.901678897160309E-16</X>
      <Y>1.7424000000000024</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>1.7423999999999975</X>
      <Y>-1.2755253271080125</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>3.4847999999999995</X>
      <Y>-1.2755253271080143</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>2.6135999999999955</X>
      <Y>-2.7844879906620204</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <X>4.3560000000000016</X>
      <Y>0.23343733644599171</Y>
      <Hidden>false</Hidden>
    </Node>
    <Node>
      <Decorator xsi:type="EndDecorator">
        <Length>0.2</Length>
        <Angle>0</Angle>
        <Color>Transparent</Color>
      </Decorator>
      <X>5.2272000000000025</X>
      <Y>1.7424</Y>
      <Hidden>false</Hidden>
    </Node>
  </Nodes>
  <EdgesID>
    <SaveEdge>
      <Start>0</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>2</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>4</Start>
      <End>3</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>0</Start>
      <End>4</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>3</Start>
      <End>5</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>7</Start>
      <End>6</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>5</Start>
      <End>7</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>2</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>6</Start>
      <End>8</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>9</Start>
      <End>1</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
    <SaveEdge>
      <Start>8</Start>
      <End>9</End>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveEdge>
  </EdgesID>
  <FacesID>
    <SaveFace>
      <Nodes>
        <int>1</int>
        <int>0</int>
        <int>2</int>
      </Nodes>
      <Decorator xsi:type="TetrisDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Shapes>
          <ArrayOfNode>
            <Node>
              <X>1.4999999999999996</X>
              <Y>0.13397459621556118</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.49999999999999933</X>
              <Y>0.13397459621556185</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>0.99999999999999856</X>
              <Y>-0.73205080756887753</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
          <ArrayOfNode>
            <Node>
              <X>1.4999999999999996</X>
              <Y>0.13397459621556118</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>1.9999999999999991</X>
              <Y>-0.73205080756887875</Y>
              <Hidden>false</Hidden>
            </Node>
            <Node>
              <X>2.5000000000000009</X>
              <Y>0.13397459621555996</Y>
              <Hidden>false</Hidden>
            </Node>
          </ArrayOfNode>
        </Shapes>
        <Indexes>
          <int>3</int>
          <int>6</int>
        </Indexes>
        <Color>Yellow</Color>
        <MarginSize>0.05</MarginSize>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>0</int>
        <int>3</int>
      </Nodes>
      <Decorator xsi:type="TriangleDecorator">
        <DeltaX>0</DeltaX>
        <DeltaY>0</DeltaY>
        <Angle>0</Angle>
        <ExtraScale>1</ExtraScale>
        <Count>2</Count>
        <Color>Gold</Color>
      </Decorator>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>3</int>
        <int>0</int>
        <int>4</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>3</int>
        <int>5</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>5</int>
        <int>6</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>6</int>
        <int>5</int>
        <int>7</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>6</int>
        <int>8</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>2</int>
        <int>8</int>
        <int>1</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
    <SaveFace>
      <Nodes>
        <int>1</int>
        <int>8</int>
        <int>9</int>
      </Nodes>
      <GraphElementColor>Transparent</GraphElementColor>
    </SaveFace>
  </FacesID>
  <MetaData>
    <PuzzleTitle>Square/SquarePuzzle_1x1</PuzzleTitle>
    <BackgroundColor>LightGray</BackgroundColor>
    <ForegroundColor>DarkGray</ForegroundColor>
    <EdgeWidth>0.2</EdgeWidth>
    <TetrisTemplate>
      <Shapes>
        <ArrayOfNode>
          <Node>
            <X>3.4848000000000003</X>
            <Y>1.7424000000000002</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.7424000000000002</X>
            <Y>1.7424000000000002</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.6135999999999995</X>
            <Y>0.23343733644599379</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2.6135999999999995</X>
            <Y>0.23343733644599379</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.7424000000000002</X>
            <Y>1.7424000000000002</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.87119999999999886</X>
            <Y>0.23343733644599501</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>0.87119999999999886</X>
            <Y>0.23343733644599501</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.7424000000000002</X>
            <Y>1.7424000000000002</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.901678897160309E-16</X>
            <Y>1.7424000000000024</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2.6135999999999995</X>
            <Y>0.23343733644599379</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>0.87119999999999886</X>
            <Y>0.23343733644599501</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.7423999999999975</X>
            <Y>-1.2755253271080125</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2.6135999999999995</X>
            <Y>0.23343733644599379</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.7423999999999975</X>
            <Y>-1.2755253271080125</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.4847999999999995</X>
            <Y>-1.2755253271080143</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3.4847999999999995</X>
            <Y>-1.2755253271080143</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>1.7423999999999975</X>
            <Y>-1.2755253271080125</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>2.6135999999999955</X>
            <Y>-2.7844879906620204</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2.6135999999999995</X>
            <Y>0.23343733644599379</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.4847999999999995</X>
            <Y>-1.2755253271080143</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4.3560000000000016</X>
            <Y>0.23343733644599171</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>2.6135999999999995</X>
            <Y>0.23343733644599379</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4.3560000000000016</X>
            <Y>0.23343733644599171</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>3.4848000000000003</X>
            <Y>1.7424000000000002</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
        <ArrayOfNode>
          <Node>
            <X>3.4848000000000003</X>
            <Y>1.7424000000000002</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>4.3560000000000016</X>
            <Y>0.23343733644599171</Y>
            <Hidden>false</Hidden>
          </Node>
          <Node>
            <X>5.2272000000000025</X>
            <Y>1.7424</Y>
            <Hidden>false</Hidden>
          </Node>
        </ArrayOfNode>
      </Shapes>
    </TetrisTemplate>
    <TetrisScale>0.2</TetrisScale>
    <FaceDecorationScale>1</FaceDecorationScale>
    <ExportWidth>768</ExportWidth>
    <ExportHeight>768</ExportHeight>
    <LineColor>Yellow</LineColor>
  </MetaData>
</SaveState>